### ISSUE TITLE
Closing </html> tag

### ISSUE THREAD

**Issue by aubreywullschleger** [mcnoble/teacozy#1]
Subtlety for errors!  Make sure to use a closing `</html>` tag after your closing `</body>` tag.

**Comment by mcnoble** [comment]
Awesome @aubreywullschleger  - thanks so much for all of the comments and feedback. It's amazing how quickly things get easier. The Tortoise project  has gone so much better after getting through teacozy and the SecretAgentSupply. Thank you again for the links to additional reading and helpful feedback.
